services:
  postgres:
    image: postgres
    container_name: oidc_provider
    restart: unless-stopped

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: oidc_provider_db

    volumes:
      - postgres_data:/var/lib/postgresql/

volumes:
  postgres_data:
